interaction:
  actionCardDelayMs: 1000
  eventCardMinDelayMs: 10000
  eventCardMaxDelayMs: 20000
  eventCardMinDurationMs: 30000
  eventCardMaxDurationMs: 60000
  slotGroups:
    - id: technology
      type: action-card
      label:
        de: Technologie
        en: Technology
      assets:
        markerSlotActive:
          url: slots/marker-slot-yellow_x-121_y-121.webp
        markerSlotInactive:
          url: slots/marker-slot-inactive_x-121_y-121.webp
      slots:
        - markerSlot: { id: technology-ms-1, x: 186, y: 744, angle: 90 }
          cardSlot: { id: technology-cs-1, x: 548, y: 635, angle: 90 }
        - markerSlot: { id: technology-ms-2, x: 186, y: 1000, angle: 90 }
          cardSlot: { id: technology-cs-2, x: 548, y: 890, angle: 90 }
        - markerSlot: { id: technology-ms-3, x: 186, y: 1255, angle: 90 }
          cardSlot: { id: technology-cs-3, x: 548, y: 1146, angle: 90 }
      cards:
        - parameterTransformId: (T) Triple Diamantglas
          url: cards/technology/triple-diamond-glass.webp
        - parameterTransformId: (T) KI-Automatisierung
          url: cards/technology/ai-automation.webp
        - parameterTransformId: (T) Modular smartphone
          url: cards/technology/modular-smartphone.webp
        - parameterTransformId: (T) Planed Obsol
          url: cards/technology/planned-obsolescence.webp
        - parameterTransformId: (T) Software Upgrade
          url: cards/technology/software-upgrade.webp
    - id: policy
      type: action-card
      label:
        de: Regelung
        en: Policy
      assets:
        markerSlotActive:
          url: slots/marker-slot-yellow_x-121_y-121.webp
        markerSlotInactive:
          url: slots/marker-slot-inactive_x-121_y-121.webp
      slots:
        - markerSlot: { id: policy-ms-1, x: 1408, y: 2007, angle: 0 }
          cardSlot: { id: policy-cs-1, x: 1299, y: 1645, angle: 0 }
        - markerSlot: { id: policy-ms-2, x: 1664, y: 2007, angle: 0 }
          cardSlot: { id: policy-cs-2, x: 1554, y: 1645, angle: 0 }
        - markerSlot: { id: policy-ms-3, x: 1920, y: 2007, angle: 0 }
          cardSlot: { id: policy-cs-3, x: 1811, y: 1645, angle: 0 }
      cards:
        - parameterTransformId: (P) Schul-Repair-Café
          url: cards/policy/school-repair-cafe.webp
        - parameterTransformId: (P) Extreme Öko-Steuer
          url: cards/policy/extreme-eco-tax.webp
        - parameterTransformId: (P) Handy-Abo
          url: cards/policy/handy-abo.webp
        - parameterTransformId: (P) Recycle-Prämie
          url: cards/policy/recycle-bonus.webp
        - parameterTransformId: (P) Wartungsvertrag
          url: cards/policy/wartungsvertrag.webp
        - parameterTransformId: (P) Jugendschutz
          url: cards/policy/youth-protection.webp
        - parameterTransformId: (P) Ein-Telefon-Gesetz
          url: cards/policy/one-phone-law.webp
        - parameterTransformId: (P) BYOD
          url: cards/policy/byod.webp
        - parameterTransformId: (P) Handy Detox Day
          url: cards/policy/handy-detox-day.webp
    - id: event
      type: event-card
      label:
        de: Ereignisse
        en: Events
      assets:
        markerSlotActive:
          url: slots/marker-slot-yellow_x-121_y-121.webp
        markerSlotInactive:
          url: slots/marker-slot-inactive_x-121_y-121.webp
      markerSlot: { id: event-ms-1, x: 2211, y: 216, angle: 180 }
      cardSlots:
        - { id: event-cs-1, x: 2075, y: 324, angle: 180 }
        - { id: event-cs-2, x: 1821, y: 324, angle: 180 }
        - { id: event-cs-3, x: 1563, y: 324, angle: 180 }
      cards:
        - parameterTransformId: (E) Weltweite Chip-Krise
          url: cards/event/global-chip-crisis.webp
        - parameterTransformId: (E) Neues Ananas Phone
          url: cards/event/new-pineapple-phone.webp
        - parameterTransformId: (E) Sicherheitslücke
          url: cards/event/security-gap.webp
        - parameterTransformId: (E) Transport Streik
          url: cards/event/transportstreik.webp
        - parameterTransformId: (E) Deponie Streik
          url: cards/event/landfill-strike.webp
    - id: reduce
      type: basic
      label:
        de: Reduzieren
        en: Reduce
      assets:
        markerSlotActive:
          url: slots/marker-slot-cyan_x-121_y-121.webp
        markerSlotInactive:
          url: slots/marker-slot-inactive_x-121_y-121.webp
      markerSlots:
        - { id: reduce-ms-1, x: 1574, y: 1171, angle: 0 }
        - { id: reduce-ms-2, x: 1821, y: 1229, angle: 0 }
        - { id: reduce-ms-3, x: 2066, y: 1279, angle: 0 }
      parameterTransformIds: [reduce, reduce, reduce]
    - id: reuse
      type: basic
      label:
        de: |
          Wieder-
          verwenden
        en: Reuse
      assets:
        markerSlotActive:
          url: slots/marker-slot-cyan_x-121_y-121.webp
        markerSlotInactive:
          url: slots/marker-slot-inactive_x-121_y-121.webp
      markerSlots:
        - { id: reuse-ms-1, x: 3626, y: 902, angle: -90 }
        - { id: reuse-ms-2, x: 3634, y: 1155, angle: -90 }
        - { id: reuse-ms-3, x: 3644, y: 1410, angle: -90 }
      parameterTransformIds: [reuse, reuse, reuse]
    - id: repair
      type: basic
      label:
        de: Reparieren
        en: Repair
      assets:
        markerSlotActive:
          url: slots/marker-slot-cyan_x-121_y-121.webp
        markerSlotInactive:
          url: slots/marker-slot-inactive_x-121_y-121.webp
      markerSlots:
        - { id: repair-ms-1, x: 1413, y: 904, angle: 180 }
        - { id: repair-ms-2, x: 1646, y: 798, angle: 180 }
        - { id: repair-ms-3, x: 1876, y: 693, angle: 180 }
      parameterTransformIds: [repair, repair, repair]
    - id: refurbish
      type: basic
      label:
        de: Erneuern
        en: Refurbish
      assets:
        markerSlotActive:
          url: slots/marker-slot-cyan_x-121_y-121.webp
        markerSlotInactive:
          url: slots/marker-slot-inactive_x-121_y-121.webp
      markerSlots:
        - { id: refurbish-ms-1, x: 2686, y: 1884, angle: 0 }
        - { id: refurbish-ms-2, x: 2935, y: 1829, angle: 0 }
        - { id: refurbish-ms-3, x: 3180, y: 1774, angle: 0 }
      parameterTransformIds: [refurbish, refurbish, refurbish]
    - id: recycle
      type: basic
      label:
        de: |
          Wieder-
          verwerten
        en: Recycle
      assets:
        markerSlotActive:
          url: slots/marker-slot-cyan_x-121_y-121.webp
        markerSlotInactive:
          url: slots/marker-slot-inactive_x-121_y-121.webp
      markerSlots:
        - { id: recycle-ms-1, x: 507, y: 476, angle: 180 }
        - { id: recycle-ms-2, x: 709, y: 320, angle: 180 }
        - { id: recycle-ms-3, x: 911, y: 167, angle: 180 }
      parameterTransformIds: [recycle, recycle, recycle]
