layers:
  - url: background_static_x0_y0.webp
    condition: 'true'
  - url: repair_background_x1156_y468.webp
    condition: 'true'
  - modelVisualization
  - url: refurbish_shop_x2419_y1433.webp
    condition: 'true'
  - url: government_x879_y1707.webp
    condition: 'true'
  - url: broken_phones3_x2353_y685.webp
    condition: 'stocks.supplyOfBrokenPhones > 40000'
  - url: broken_cell2_x2400_y802.webp
    condition: 'stocks.supplyOfBrokenPhones > 100000'
  - url: broken_phones1_x2286_y877.webp
    condition: 'stocks.supplyOfBrokenPhones > 300000'
  - url: broken_cell1_x2352_y763.webp
    condition: 'stocks.supplyOfBrokenPhones > 500000'
  - url: broken_cellx_x2396_y862.webp
    condition: 'stocks.supplyOfBrokenPhones > 700000'
  - url: broken_cell3_x2307_y801.webp
    condition: 'stocks.supplyOfBrokenPhones > 1300000'
  - url: factory-smoke_x958_y1363.webp
    condition:
      '!parameters.userdata?.policy?.["(P) Ein-Telefon-Gesetz"] &&
      !parameters.userdata?.event?.["(E) Weltweite Chip-Krise"] &&
      !parameters.userdata?.event?.["(E) Transport Streik"]'
  - url: factory-building_x692_y1343.webp
    condition: 'true'
  - url: factory_pipe_x673_y997.webp
    condition: 'true'
  - url: factory_workerright_x542_y1039.webp
    condition: 'true'
  - url: factory_workers1_x589_y905.webp
    condition: 'true'
  - url: factory_workermiddle_x568_y1077.webp
    condition: 'true'
  - url: handiesgarbage_people_x2594_y417.webp
    condition: 'true'
  - url: handiesgarbage_x2736_y435.webp
    condition: 'true'
  - url: garbage-pile1_x2890_y429.webp
    condition: 'stocks.supplyOfDisposedPhones > 700000'
  - url: garbage-pile2_x2819_y425.webp
    condition: 'stocks.supplyOfDisposedPhones > 3000000'
  - url: garbage_pile3_x2881_y432.webp
    condition: 'stocks.supplyOfDisposedPhones > 10000000'
  - url: landfill_static_x3384_y-4.webp
    condition: 'true'
  - url: nature_static_x-8_y1644.webp
    condition: 'true'
  - url: news_agency_x2692_y31.webp
    condition: 'true'
  - url: news_people_x2333_y6.webp
    condition: 'true'
  - url: recycle_plant_x802_y410.webp
    condition: 'true'
  - url: recycle_belt_x767_y542.webp
    condition: 'true'
  - url: recycle_belt2_x978_y325.webp
    condition: 'true'
  - url: recycle_man1_x813_y490.webp
    condition: 'parameters.userdata.recycle >= 2.5'
  - url: recycle_man2_x925_y340.webp
    condition: 'parameters.userdata.recycle >= 1.5'
  - url: recycle-beltempty_x638_y309.webp
    condition: 'stocks.supplyOfRecycledMaterials <= 50000'
  - url: recycle-beltanimleast_x638_y309.webp
    condition:
      'stocks.supplyOfRecycledMaterials > 50000 &&
      stocks.supplyOfRecycledMaterials<=190000'
  - url: recycle-beltanimmedium_x638_y309.webp
    condition:
      'stocks.supplyOfRecycledMaterials > 190000 &&
      stocks.supplyOfRecycledMaterials <= 290000'
  - url: recycle-beltanimmost_x638_y309.webp
    condition: 'stocks.supplyOfRecycledMaterials > 290000'
  - url: recycle_man3_x622_y453.webp
    condition: 'parameters.userdata.recycle >= 0.5'
  - url: recycle_woman_x840_y417.webp
    condition: 'true'
  - url: recycle_boxwithr_x974_y259.webp
    condition: 'true'
  - url: reduce_subwaybench_x1050_y948.webp
    condition: 'true'
  - url: reduce_girl2_x1158_y1187.webp
    condition:
      'parameters.userdata.reduce != 1 && parameters.userdata.reduce != 2 &&
      parameters.userdata.reduce != 3'
  - url: reduce_girl2talking_x1158_y1187.webp
    condition: 'parameters.userdata.reduce >= 0.5'
  - url: reduce_man_x1023_y1059.webp
    condition: 'parameters.userdata.reduce != 3'
  - url: reduce_mannophone_x1023_y1059.webp
    condition: 'parameters.userdata.reduce >= 2.5'
  - url: reduce_girl1_x1094_y1156.webp
    condition:
      'parameters.userdata.reduce != 2 && parameters.userdata.reduce != 3'
  - url: reduce_girl1talking_x1094_y1156.webp
    condition: 'parameters.userdata.reduce >= 1.5'
  - url: reduce_cellphone_x1397_y1277.webp
    condition: 'true'
  - url: reduce_walkingmanphone_x1550_y1275.webp
    condition:
      '!parameters.userdata?.policy?.["(P) Extreme Öko-Steuer"] &&
      !parameters.userdata?.policy?.["(P) Jugendschutz"] &&
      !parameters.userdata?.policy?.["(P) Ein-Telefon-Gesetz"] &&
      !parameters.userdata?.policy?.["(P) BYOD"] &&
      !parameters.userdata?.policy?.["(P) Handy Detox Day"] &&
      !parameters.userdata?.event?.["(E) Weltweite Chip-Krise"]'
  - url: reduced_walkingmannophone_x1556_y1292.webp
    condition:
      'parameters.userdata?.policy?.["(P) Extreme Öko-Steuer"] ||
      parameters.userdata?.policy?.["(P) Jugendschutz"] ||
      parameters.userdata?.policy?.["(P) Ein-Telefon-Gesetz"] ||
      parameters.userdata?.policy?.["(P) BYOD"] ||
      parameters.userdata?.policy?.["(P) Handy Detox Day"] ||
      parameters.userdata?.event?.["(E) Weltweite Chip-Krise"]'
  - url: refurbish_cellbathing_x2532_y1140.webp
    condition: 'true'
  - url: refurbish_shop_x2419_y1433.webp
    condition: 'false'
  - url: refurbish_mandesk_x2390_y1463.webp
    condition: 'true'
  - url: refurbish_man1_x2443_y1546.webp
    condition: 'parameters.userdata.refurbish >= 0.5'
  - url: refurbish-pile1_x2509_y1661.webp
    condition: 'parameters.userdata.refurbish >= 1.5'
  - url: repair_background_x1156_y468.webp
    condition: 'false'
  - url: repair_gangster_x1206_y568.webp
    condition: 'flows.acquireRepaired > 200000'
  - url: repair_woman_x1336_y546.webp
    condition: 'flows.acquireRepaired > 20000'
  - url: repair_injection_x1737_y400.webp
    condition: 'true'
  - url: repair_table_x1242_y378.webp
    condition: 'true'
  - url: repair_man1_x1399_y432.webp
    condition: 'true'
  - url: reuse_window_x2837_y914.webp
    condition: 'true'
  - url: reuse_drawer_x2912_y890.webp
    condition: 'true'
  - url: reuse_R_x3170_y997.webp
    condition: 'true'
  - url: reuse_pool_x3211_y1028.webp
    condition: 'true'
  - url: reuse_handy04_x3219_y1145.webp
    condition: 'stocks.supplyOfHibernatingPhones > 300000'
  - url: reuse_handy03_x3271_y1094.webp
    condition: 'stocks.supplyOfHibernatingPhones > 500000'
  - url: reuse_handy01_x3211_y1081.webp
    condition: 'stocks.supplyOfHibernatingPhones > 1000000'
  - url: reuse_handy02_x3256_y1042.webp
    condition: 'stocks.supplyOfHibernatingPhones > 1500000'
  - url: reuse_poolanim_x3211_y1028.webp
    condition: 'stocks.supplyOfHibernatingPhones > 30000'
  - url: reuse_foldphone_x3200_y772.webp
    condition: 'stocks.supplyOfHibernatingPhones > 10000'
  - url: easteregg_darthvader_x2076_y1896.webp
    condition: 'new Date().getDate() === 4 && (new Date().getMonth()+1) === 5'
  - url: easteregg_georgeharrison_x2234_y991.webp
    condition: 'new Date().getDate() === 25 && (new Date().getMonth()+1) === 2'
  - url: easteregg_pipie_x3277_y510.webp
    condition: 'new Date().getDate() === 14 && (new Date().getMonth()+1) === 3'
