layers:
  - url: background_static_x0_y0.webp
    condition: 'true'
  - url: repair_background_x1156_y468.webp
    condition: 'true'
  - modelVisualization
  - url: refurbish_shop_x2419_y1433.webp
    condition: 'true'
  - url: government_x879_y1707.webp
    condition: 'true'
  - url: stock-sign-kaputt_x2216_y873.webp
    condition: 'true'
  - url: broken_cell2_x2400_y802.webp
    condition: 'stocks.supplyOfBrokenPhones > 40000'
  - url: broken_phones3_x2353_y685.webp
    condition: 'stocks.supplyOfBrokenPhones > 100000'
  - url: broken_phone_x2316_y870.webp
    condition: 'stocks.supplyOfBrokenPhones > 300000'
  - url: broken_cell1_x2352_y763.webp
    condition: 'stocks.supplyOfBrokenPhones > 500000'
  - url: broken_cellx_x2396_y862.webp
    condition: 'stocks.supplyOfBrokenPhones > 700000'
  - url: broken_cell3_x2307_y801.webp
    condition: 'stocks.supplyOfBrokenPhones > 1300000'
  - url: factory-smoke_x958_y1363.webp
    condition:
      '!parameters.userdata?.policy?.["(P) Ein-Telefon-Gesetz"] &&
      !parameters.userdata?.event?.["(E) Weltweite Chip-Krise"] &&
      !parameters.userdata?.event?.["(E) Transport Streik"]'
  - url: factory_pipe_x673_y997.webp
    condition: 'true'
  - url: factory_workerright_x542_y1039.webp
    condition: 'true'
  - url: factory_workers1_x589_y905.webp
    condition: 'true'
  - url: factory_workermiddle_x568_y1077.webp
    condition: 'true'
  - url: stock-sign-fabrik_x751_y1243.webp
    condition: 'true'
  - url: factory-building_x692_y1343.webp
    condition: 'true'
  - url: stock-sign-garbage_x2752_y641.webp
    condition: 'true'
  - url: handiesgarbage_people_x2594_y417.webp
    condition: 'true'
  - url: handiesgarbage_x2736_y435.webp
    condition: 'true'
  - url: garbage-pile1_x2890_y429.webp
    condition: 'stocks.supplyOfDisposedPhones > 700000'
  - url: garbage-pile2_x2819_y425.webp
    condition: 'stocks.supplyOfDisposedPhones > 3000000'
  - url: garbage_pile3_x2881_y432.webp
    condition: 'stocks.supplyOfDisposedPhones > 10000000'
  - url: landfill_static_x3384_y-4.webp
    condition: 'true'
  - url: nature_static_x-8_y1644.webp
    condition: 'true'
  - url: news_agency_x2692_y31.webp
    condition: 'true'
  - url: news_people_x2333_y6.webp
    condition: 'true'
  - url: recycle_plant_x802_y410.webp
    condition: 'true'
  - url: recycle_belt_x767_y542.webp
    condition: 'true'
  - url: recycle_belt2_x978_y325.webp
    condition: 'true'
  - url: recycle_man1_x813_y490.webp
    condition: 'parameters.userdata.recycle >= 2.5'
  - url: recycle_man2_x925_y340.webp
    condition: 'parameters.userdata.recycle >= 1.5'
  - url: recycle-beltempty_x638_y309.webp
    condition: 'stocks.supplyOfRecycledMaterials <= 50000'
  - url: recycle-beltanimleast_x638_y309.webp
    condition:
      'stocks.supplyOfRecycledMaterials > 50000 &&
      stocks.supplyOfRecycledMaterials<=190000'
  - url: recycle-beltanimmedium_x638_y309.webp
    condition:
      'stocks.supplyOfRecycledMaterials > 190000 &&
      stocks.supplyOfRecycledMaterials <= 290000'
  - url: recycle-beltanimmost_x638_y309.webp
    condition: 'stocks.supplyOfRecycledMaterials > 290000'
  - url: recycle_man3_x622_y453.webp
    condition: 'parameters.userdata.recycle >= 0.5'
  - url: recycle_woman_x840_y417.webp
    condition: 'true'
  - url: recycle_boxwithr_x974_y259.webp
    condition: 'true'
  - url: reduce_subwaybench_x1050_y948.webp
    condition: 'true'
  - url: stock-sign-benutzung_x1171_y915.webp
    condition: 'true'
  - url: reduce_girl2_x1158_y1187.webp
    condition:
      'parameters.userdata.reduce != 1 && parameters.userdata.reduce != 2 &&
      parameters.userdata.reduce != 3'
  - url: reduce_girl2talking_x1158_y1187.webp
    condition: 'parameters.userdata.reduce >= 0.5'
  - url: reduce_man_x1023_y1059.webp
    condition: 'parameters.userdata.reduce != 3'
  - url: reduce_mannophone_x1023_y1059.webp
    condition: 'parameters.userdata.reduce >= 2.5'
  - url: reduce_girl1_x1094_y1156.webp
    condition:
      'parameters.userdata.reduce != 2 && parameters.userdata.reduce != 3'
  - url: reduce_girl1talking_x1094_y1156.webp
    condition: 'parameters.userdata.reduce >= 1.5'
  - url: reduce_cellphone_x1397_y1277.webp
    condition: 'true'
  - url: reduce_walkingmanphone_x1550_y1275.webp
    condition:
      '!parameters.userdata?.policy?.["(P) Extreme Öko-Steuer"] &&
      !parameters.userdata?.policy?.["(P) Jugendschutz"] &&
      !parameters.userdata?.policy?.["(P) Ein-Telefon-Gesetz"] &&
      !parameters.userdata?.policy?.["(P) BYOD"] &&
      !parameters.userdata?.policy?.["(P) Handy Detox Day"] &&
      !parameters.userdata?.event?.["(E) Weltweite Chip-Krise"]'
  - url: reduced_walkingmannophone_x1556_y1292.webp
    condition:
      'parameters.userdata?.policy?.["(P) Extreme Öko-Steuer"] ||
      parameters.userdata?.policy?.["(P) Jugendschutz"] ||
      parameters.userdata?.policy?.["(P) Ein-Telefon-Gesetz"] ||
      parameters.userdata?.policy?.["(P) BYOD"] ||
      parameters.userdata?.policy?.["(P) Handy Detox Day"] ||
      parameters.userdata?.event?.["(E) Weltweite Chip-Krise"]'
  - url: refurbish_cellbathing_x2532_y1140.webp
    condition: 'true'
  - url: refurbish_shop_x2419_y1433.webp
    condition: 'false'
  - url: refurbish_mandesk_x2390_y1463.webp
    condition: 'true'
  - url: refurbish_man1_x2443_y1546.webp
    condition: 'parameters.userdata.refurbish >= 0.5'
  - url: refurbish-pile1_x2509_y1661.webp
    condition: 'parameters.userdata.refurbish >= 1.5'
  - url: repair_background_x1156_y468.webp
    condition: 'false'
  - url: repair_gangster_x1206_y568.webp
    condition: 'parameters.userdata.repair >= 1.5'
  - url: repair_woman_x1336_y546.webp
    condition: 'flows.acquireRepaired > 20000'
  - url: repair_injection_x1737_y400.webp
    condition: 'true'
  - url: repair_table_x1242_y378.webp
    condition: 'true'
  - url: repair_man1_x1399_y432.webp
    condition: 'true'
  - url: reuse_window_x2837_y914.webp
    condition: 'true'
  - url: reuse_drawer_x2912_y890.webp
    condition: 'true'
  - url: reuse_R_x3170_y997.webp
    condition: 'true'
  - url: stock-sign-abandoned_x3200_y1215.webp
    condition: 'true'
  - url: reuse_pool_x3211_y1028.webp
    condition: 'true'
  - url: reuse_handy04_x3219_y1145.webp
    condition: 'stocks.supplyOfHibernatingPhones > 300000'
  - url: reuse_handy03_x3271_y1094.webp
    condition: 'stocks.supplyOfHibernatingPhones > 500000'
  - url: reuse_handy01_x3211_y1081.webp
    condition: 'stocks.supplyOfHibernatingPhones > 1000000'
  - url: reuse_handy02_x3256_y1042.webp
    condition: 'stocks.supplyOfHibernatingPhones > 1500000'
  - url: reuse_poolanim_x3211_y1028.webp
    condition: 'stocks.supplyOfHibernatingPhones > 30000'
  - url: reuse_foldphone_x3200_y772.webp
    condition: 'stocks.supplyOfHibernatingPhones > 10000'
  - url: easteregg_darthvader_x2076_y1896.webp
    condition: 'new Date().getDate() === 4 && (new Date().getMonth()+1) === 5'
  - url: easteregg_georgeharrison_x2234_y991.webp
    condition: 'new Date().getDate() === 25 && (new Date().getMonth()+1) === 2'
  - url: easteregg_pipie_x3277_y510.webp
    condition: 'new Date().getDate() === 14 && (new Date().getMonth()+1) === 3'
  - slots
  - scores
  # Circularity score
  # Emoji selection:
  # - map the interval [0, 1] to [-1, 1] linearly
  # - apply x |-> x ^ 3 (steeper boundaries, plateau in the middle)
  # - map the interval [-1, 1] to [0, 5] linearly
  # - round down to get the emoji index
  # - formula: Math.floor((5 * ((2 * variables.circularityScore - 1) ** 3 + 1)) / 2)
  # - piecewise definition (by computing the discontinuities of the function):
  #     [0.0, 0.07828) -> 0 (very bad)
  #     [0.07828, 0.2076) -> 1 (bad)
  #     [0.2076, 0.7924) -> 2 (neutral)
  #     [0.7924, 0.92172) -> 3 (good)
  #     [0.92172, 1.0] -> 4 (very good)
  - url: scores/very-bad_x3434_y1960.png
    condition: 'variables.circularityScore < 0.07828'
  - url: scores/bad_x3434_y1960.png
    condition:
      'variables.circularityScore >= 0.07828 && variables.circularityScore <
      0.2076'
  - url: scores/neutral_x3434_y1960.png
    condition:
      'variables.circularityScore >= 0.2076 && variables.circularityScore <
      0.7924'
  - url: scores/good_x3434_y1960.png
    condition:
      'variables.circularityScore >= 0.7924 && variables.circularityScore <
      0.92172'
  - url: scores/very-good_x3434_y1960.png
    condition: 'variables.circularityScore >= 0.92172'
  # Coverage score
  # Emoji selection:
  # - for the interval [0, 1], apply the mapping used for the circularity score
  # - for the interval (1, 2], linearly map 1 to 1 and 2 to 0 (mirror),
  #   then apply the mapping used for the circularity score
  # - formula: Math.floor(5 * (((2 * (1 - Math.abs(Math.min(variables.coverageScore, 2) - 1)) - 1) ** 3) + 1) / 2)
  # - piecewise definition (by computing the discontinuities of the function):
  #     [0.0, 0.07828) ∪ [1.92172, ∞) -> 0 (very bad)
  #     [0.07828, 0.2076) ∪ [1.7924, 1.92172) -> 1 (bad)
  #     [0.2076, 0.7924) ∪ [1.2076, 1.7924) -> 2 (neutral)
  #     [0.7924, 0.92172) ∪ [1.07828, 1.2076) -> 3 (good)
  #     [0.92172, 1.07828) -> 4 (very good)
  - url: scores/very-bad_x209_y3.png
    condition:
      '(variables.coverageScore < 0.07828 ) || (variables.coverageScore >=
      1.92172)'
  - url: scores/bad_x209_y3.png
    condition:
      '(variables.coverageScore >= 0.07828 && variables.coverageScore < 0.2076)
      || (variables.coverageScore >= 1.7924 && variables.coverageScore <
      1.92172)'
  - url: scores/neutral_x209_y3.png
    condition:
      '(variables.coverageScore >= 0.2076 && variables.coverageScore < 0.7924)
      || (variables.coverageScore >= 1.2076 && variables.coverageScore < 1.7924)'
  - url: scores/good_x209_y3.png
    condition:
      '(variables.coverageScore >= 0.7924 && variables.coverageScore < 0.92172)
      || (variables.coverageScore >= 1.07828 && variables.coverageScore <
      1.2076)'
  - url: scores/very-good_x209_y3.png
    condition:
      'variables.coverageScore >= 0.92172 && variables.coverageScore < 1.07828'
  # Speech bubbles: Refurbish
  - url: speech bubbles/R16_x2740_y1284.webp
    condition:
      'parameters.userdata.refurbish != 3 && parameters.userdata.refurbish != 2
      && parameters.userdata.refurbish != 1 && stocks.supplyOfHibernatingPhones
      > 40000'
    reset: true
  - url: speech bubbles/R17_x2526_y1365.webp
    condition: 'parameters.userdata.refurbish >= 0.5'
    reset: true
  - url: speech bubbles/R18_x2345_y1410.webp
    condition: 'parameters.userdata.refurbish >= 1.5'
    reset: true
  - url: speech bubbles/R19_x2785_y1444.webp
    condition: 'parameters.userdata.refurbish >= 2.5'
    reset: true
  # Speech bubbles: Repair
  - url: speech bubbles/R12_x1745_y275.webp
    condition:
      'parameters.userdata.repair != 3 && parameters.userdata.repair != 2 &&
      parameters.userdata.repair != 1 && stocks.supplyOfBrokenPhones > 40000'
    reset: true
  - url: speech bubbles/R13_x1395_y415.webp
    condition: 'parameters.userdata.repair >= 0.5'
    reset: true
  - url: speech bubbles/R14_x1466_y502.webp
    condition: 'parameters.userdata.repair >= 1.5'
    reset: true
  - url: speech bubbles/R15_x1198_y566.webp
    condition: 'parameters.userdata.repair >= 2.5'
    reset: true
  # Speech bubbles: Reuse
  - url: speech bubbles/R8_x3122_y817.webp
    condition:
      'parameters.userdata.reuse != 3 && parameters.userdata.reuse != 2 &&
      parameters.userdata.reuse != 1'
    reset: true
  - url: speech bubbles/R9_x2907_y845.webp
    condition: 'parameters.userdata.reuse >= 0.5'
    reset: true
  - url: speech bubbles/R10_x2933_y986.webp
    condition: 'parameters.userdata.reuse >= 1.5'
    reset: true
  - url: speech bubbles/R11_x2821_y949.webp
    condition: 'parameters.userdata.reuse >= 2.5'
    reset: true
  # Speech bubbles: Reduce
  - url: speech bubbles/R2_x1360_y1284.webp
    condition:
      'parameters.userdata.reduce != 3 && parameters.userdata.reduce != 2 &&
      parameters.userdata.reduce != 1'
    reset: true
  - url: speech bubbles/R3_x1275_y1132.webp
    condition: 'parameters.userdata.reduce >= 0.5'
    reset: true
  - url: speech bubbles/R4_x1201_y991.webp
    condition: 'parameters.userdata.reduce >= 1.5'
    reset: true
  - url: speech bubbles/R5_x1019_y996.webp
    condition: 'parameters.userdata.reduce >= 2.5'
    reset: true
  # Speech bubbles: Recycle
  - url: speech bubbles/R20_x678_y542.webp
    condition:
      'parameters.userdata.recycle != 3 && parameters.userdata.recycle != 2 &&
      parameters.userdata.recycle != 1'
    reset: true
  - url: speech bubbles/R21_x785_y326.webp
    condition: 'parameters.userdata.recycle >= 0.5'
    reset: true
  - url: speech bubbles/R22_x573_y389.webp
    condition: 'parameters.userdata.recycle >= 1.5'
    reset: true
  - url: speech bubbles/R23_x908_y414.webp
    condition: 'parameters.userdata.recycle >= 2.5'
    reset: true
  # Speech bubbles: Index
  - url: speech bubbles/R30_x3330_y1872.webp
    condition: 'variables.circularityScore < 0.078'
    reset: true
  - url: speech bubbles/R31_x485_y1584.webp
    condition: 'variables.circularityScore < 0.2'
    reset: true
  - url: speech bubbles/R6_x945_y1248.webp
    condition: '(variables.coverageScore < 0.8 )'
    reset: true
  - url: speech bubbles/R7_x901_y1241.webp
    condition: '(variables.coverageScore > 1.4 )'
    reset: true
  # Speech bubbles: Cards
  - url: speech bubbles/R28_x2570_y122.webp
    condition: 'typeof parameters.userdata?.event === "undefined"'
    reset: true
  - url: speech bubbles/R29_x2306_y142.webp
    condition: 'typeof parameters.userdata?.event !== "undefined"'
    reset: true
  - url: speech bubbles/R25_x1011_y1725.webp
    condition: 'typeof parameters.userdata?.policy === "undefined"'
    reset: true
  - url: speech bubbles/R26_x674_y1130.webp
    condition: 'typeof parameters.userdata?.technology === "undefined"'
    reset: true
  # Speech bubbles: Other conditions
  - url: speech bubbles/R27_x2305_y741.webp
    condition: 'stocks.supplyOfBrokenPhones <= 40000'
    reset: true
